use_frameworks!

platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'MXBase_Example' do
  pod 'MXBase', :path => '../'

  target 'MXBase_Tests' do
    inherit! :search_paths

    
  end
end
